const AUTH_START = "AUTH_START";
const AUTH_FINISH = "AUTH_FINISH";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_ERROR = "AUTH_ERROR";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const REDIRECT_PATH = "REDIRECT_PATH";
const CURRENT_USER = "CURRENT_USER";
const UPDATE_USER = "UPDATE_USER";
const POLL_GET = "POLL_GET";
const POLL_ERROR = "POLL_ERROR";
export {
  POLL_GET,
  POLL_ERROR,
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_FINISH,
  AUTH_ERROR,
  AUTH_LOGOUT,
  REDIRECT_PATH,
  CURRENT_USER,
  UPDATE_USER,
};
